profiles:
- name: github
  provider: github
  token: your_github_token
  server: https://github.com
- name: jenkins
  provider: jenkins
  token: your_jenkins_token
  server: https://jenkins.example.com
current-profile: github
